language: node_js
node_js:
- '12.13'

before_script:
  - npm run setup
  - npm run build


script:
  - npm run test

after_success: 
  - npm pack

deploy:
  provider: npm
  email: kbirger@gmail.com
  api_key:
    secure: W3LqUeaKxZ+eAcM08g001g4UxQNfVRLIbkivMQITbp0cbj957Z/lAZ50a9CSZyYlAvEVXWugvvZiWgL1eqWTw+1ZjFBDlF5w/dkhOG7yn5dZr1IXw7Oq5KFVMq37QPVautHCrK15ro99mhVLu+kF2oXyqa9GjzjYEiSyqwRt+uu14QtmvT0tqiSOxCcAvBp/QTbXAkFloPSHrBybKzatu3ItEluXqeKT0//nPNv4qY4wiYGbpCIzUoi+o1es5Go1aQB7ZgjfVkhjf0B+p4Iro5fH8eLWx1aJS2Xo+PduxWJ86NBQgb1SPDbMl+fm3eGSNi/KqDhsULyEXm2prhmCXHRQnX1/EBj3W4Or+kPjT1XrHEthoaczptQgAk466JaSqgxMAUTJuSzPP9ANMqO6t+7E1E1VfRWWTsObhwgBgoFAi89r4t4Ut8tm/TrV3D1l6RrpUoVQWMoOqWqTaetBqeyynfZDp9uLyYnZthU4f4NorS/DekzrltR5Ux2IRp6B1kX9uvpfeP8Soq6X/arJVX4A+GLopIaqRZdzjcPQP49chPTaIiWawk6BOYWIvbqC3uvdxk2QVME/yky9864vVDYa6p7CUs3EVd6K7vngPnIZqcH8dqTlv4dt2SQCT5duXzX1uL3abi+CTTpnJBvM0iDmGjiTKs5K/91APnqT9O8=
  
  on:
    branch: master
  skip_cleanup: true
